# Generated by Django 4.2.2 on 2023-07-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=70)),
                ('prenom', models.CharField(max_length=70)),
                ('N_Tele', models.CharField(max_length=70)),
                ('Email', models.CharField(max_length=70)),
                ('Matricule', models.CharField(max_length=70)),
                ('Date_reservation', models.DateField()),
                ('Data_retour', models.DateField()),
            ],
        ),
    ]
