# Generated by Django 4.2.2 on 2023-07-17 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_sys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voiture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=70)),
                ('modele', models.CharField(max_length=70)),
                ('matricule', models.CharField(max_length=70)),
                ('description', models.CharField(max_length=70)),
            ],
        ),
    ]
