# Generated by Django 4.2.2 on 2023-07-18 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location_sys', '0002_voiture'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='CNE',
            field=models.CharField(default=0, max_length=70, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='voiture',
            name='matricule',
            field=models.CharField(max_length=70, unique=True),
        ),
        migrations.CreateModel(
            name='Voiture_reserver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_sys.client')),
                ('voiture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_sys.voiture')),
            ],
        ),
    ]
