# Generated by Django 4.2.2 on 2023-07-18 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_sys', '0003_client_cne_alter_voiture_matricule_voiture_reserver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='CNE',
            field=models.CharField(default='', max_length=70, unique=True),
        ),
    ]
