# Generated by Django 4.2.2 on 2023-07-19 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_sys', '0005_voiture_reserver_alter_voiture_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiture',
            name='image',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
