# Generated by Django 4.2.2 on 2023-07-20 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_sys', '0007_remove_voiture_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiture',
            name='prix',
            field=models.FloatField(default=0.0),
        ),
    ]
