# Generated by Django 4.2.3 on 2023-07-23 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_sys', '0009_client_nomvoiture'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiture',
            name='carImage',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
