# Generated by Django 4.2.3 on 2023-07-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_sys', '0011_alter_client_cne'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_res',
            field=models.BooleanField(default=True),
        ),
    ]
