# Generated by Django 4.2.3 on 2023-07-30 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_sys', '0012_client_client_res'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='prix',
            field=models.FloatField(default=0.0),
        ),
    ]
