# Generated by Django 4.2.3 on 2023-08-02 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_sys', '0013_client_prix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='prix',
        ),
        migrations.AlterField(
            model_name='client',
            name='Data_retour',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='client',
            name='Date_reservation',
            field=models.DateTimeField(),
        ),
    ]
