# Generated by Django 4.2.3 on 2023-08-02 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location_sys', '0014_remove_client_prix_alter_client_data_retour_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='Data_retour',
            new_name='Date_retour',
        ),
    ]
