# Generated by Django 4.2.3 on 2023-08-02 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_sys', '0015_rename_data_retour_client_date_retour'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='prix',
            field=models.FloatField(default=0.0),
        ),
    ]
