# Generated by Django 4.2.3 on 2023-08-03 03:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_sys', '0016_client_prix'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='today',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
