# Generated by Django 4.2.3 on 2023-08-03 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_sys', '0017_client_today'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
