# Generated by Django 4.2.3 on 2023-08-07 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_sys', '0018_prix'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField()),
                ('prix', models.FloatField(default=0.0)),
            ],
        ),
    ]
